#ifndef __WAVE_FORMAT_H
#define __WAVE_FORMAT_H

#define WAVE_FORMAT_CODE_LENGTH 2

extern char WAVE_FORMAT_PCM[WAVE_FORMAT_CODE_LENGTH];
extern char WAVE_FORMAT_IEEE_FLOAT[WAVE_FORMAT_CODE_LENGTH];
extern char WAVE_FORMAT_ALAW[WAVE_FORMAT_CODE_LENGTH]; 
extern char WAVE_FORMAT_MULAW[WAVE_FORMAT_CODE_LENGTH];
extern char WAVE_FORMAT_EXTENSIBLE[WAVE_FORMAT_CODE_LENGTH];

#endif

